apiVersion: v1
kind: Pod
metadata:
  name: app-needs-config
spec:
  containers:
  - name: main-app
    image: nginx
    env:
      - name: MY_SPECIAL_CONFIG
        valueFrom:
          configMapKeyRef:
            name: my-nonexistent-config
            key: my-key
