apiVersion: v1
kind: Pod
metadata:
  name: app-with-failing-init
spec:
  initContainers:
  - name: setup-work
    image: busybox:1.28
    command: ["sh", "-c", "exit 1"]
  containers:
  - name: main-app
    image: nginx
