apiVersion: v1
kind: Pod
metadata:
  name: oom-pod
spec:
  containers:
  - name: memory-eater
    image: perl
    command: ["perl", "-e", "my @a; while(1){ push @a, ' ' x 1024*1024; }"]
    resources:
      requests:
        memory: "16Mi"
      limits:
        memory: "32Mi"
